// Country configurations for address forms
export interface CountryConfig {
    code: string;
    name: string;
    postalCodeLabel: string;
    postalCodePattern?: RegExp;
    stateLabel: string;
    hasState: boolean;
    states?: string[];
    addressLine2Label: string;
}

export const COUNTRIES: CountryConfig[] = [
    {
        code: 'US',
        name: 'United States',
        postalCodeLabel: 'ZIP Code',
        postalCodePattern: /^\d{5}(-\d{4})?$/,
        stateLabel: 'State',
        hasState: true,
        states: [
            'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware',
            'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
            'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
            'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
            'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
            'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
            'West Virginia', 'Wisconsin', 'Wyoming', 'District of Columbia',
        ],
        addressLine2Label: 'Apartment, suite, etc. (optional)',
    },
    {
        code: 'CA',
        name: 'Canada',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d$/,
        stateLabel: 'Province',
        hasState: true,
        states: [
            'Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador',
            'Northwest Territories', 'Nova Scotia', 'Nunavut', 'Ontario', 'Prince Edward Island',
            'Quebec', 'Saskatchewan', 'Yukon',
        ],
        addressLine2Label: 'Apartment, suite, etc. (optional)',
    },
    {
        code: 'GB',
        name: 'United Kingdom',
        postalCodeLabel: 'Postcode',
        postalCodePattern: /^[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}$/i,
        stateLabel: 'County',
        hasState: false,
        addressLine2Label: 'Flat, suite, etc. (optional)',
    },
    {
        code: 'AU',
        name: 'Australia',
        postalCodeLabel: 'Postcode',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'State/Territory',
        hasState: true,
        states: [
            'Australian Capital Territory', 'New South Wales', 'Northern Territory', 'Queensland',
            'South Australia', 'Tasmania', 'Victoria', 'Western Australia',
        ],
        addressLine2Label: 'Apartment, unit, etc. (optional)',
    },
    {
        code: 'DE',
        name: 'Germany',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'State',
        hasState: true,
        states: [
            'Baden-Württemberg', 'Bavaria', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hesse',
            'Lower Saxony', 'Mecklenburg-Vorpommern', 'North Rhine-Westphalia', 'Rhineland-Palatinate',
            'Saarland', 'Saxony', 'Saxony-Anhalt', 'Schleswig-Holstein', 'Thuringia',
        ],
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'FR',
        name: 'France',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'IT',
        name: 'Italy',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'ES',
        name: 'Spain',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'MX',
        name: 'Mexico',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'State',
        hasState: true,
        states: [
            'Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche', 'Chiapas', 'Chihuahua',
            'Coahuila', 'Colima', 'Durango', 'Guanajuato', 'Guerrero', 'Hidalgo', 'Jalisco', 'México',
            'Michoacán', 'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro', 'Quintana Roo',
            'San Luis Potosí', 'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatán', 'Zacatecas',
        ],
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'BR',
        name: 'Brazil',
        postalCodeLabel: 'CEP',
        postalCodePattern: /^\d{5}-?\d{3}$/,
        stateLabel: 'State',
        hasState: true,
        states: [
            'Acre', 'Alagoas', 'Amapá', 'Amazonas', 'Bahia', 'Ceará', 'Distrito Federal', 'Espírito Santo',
            'Goiás', 'Maranhão', 'Mato Grosso', 'Mato Grosso do Sul', 'Minas Gerais', 'Pará', 'Paraíba',
            'Paraná', 'Pernambuco', 'Piauí', 'Rio de Janeiro', 'Rio Grande do Norte', 'Rio Grande do Sul',
            'Rondônia', 'Roraima', 'Santa Catarina', 'São Paulo', 'Sergipe', 'Tocantins',
        ],
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'IN',
        name: 'India',
        postalCodeLabel: 'PIN Code',
        postalCodePattern: /^\d{6}$/,
        stateLabel: 'State',
        hasState: true,
        states: [
            'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat',
            'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh',
            'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan',
            'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
        ],
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'JP',
        name: 'Japan',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{3}-?\d{4}$/,
        stateLabel: 'Prefecture',
        hasState: true,
        states: [
            'Aichi', 'Akita', 'Aomori', 'Chiba', 'Ehime', 'Fukui', 'Fukuoka', 'Fukushima', 'Gifu', 'Gunma',
            'Hiroshima', 'Hokkaido', 'Hyogo', 'Ibaraki', 'Ishikawa', 'Iwate', 'Kagawa', 'Kagoshima',
            'Kanagawa', 'Kochi', 'Kumamoto', 'Kyoto', 'Mie', 'Miyagi', 'Miyazaki', 'Nagano', 'Nagasaki',
            'Nara', 'Niigata', 'Oita', 'Okayama', 'Okinawa', 'Osaka', 'Saga', 'Saitama', 'Shiga',
            'Shimane', 'Shizuoka', 'Tochigi', 'Tokushima', 'Tokyo', 'Tottori', 'Toyama', 'Wakayama',
            'Yamagata', 'Yamaguchi', 'Yamanashi',
        ],
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    // European Countries
    {
        code: 'AT',
        name: 'Austria',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'State',
        hasState: true,
        states: [
            'Burgenland', 'Carinthia', 'Lower Austria', 'Salzburg', 'Styria', 'Tyrol', 'Upper Austria', 'Vienna', 'Vorarlberg',
        ],
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'BE',
        name: 'Belgium',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'CH',
        name: 'Switzerland',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'Canton',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'NL',
        name: 'Netherlands',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4} ?[A-Z]{2}$/i,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'SE',
        name: 'Sweden',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{3} ?\d{2}$/,
        stateLabel: 'County',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'NO',
        name: 'Norway',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'County',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'DK',
        name: 'Denmark',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'FI',
        name: 'Finland',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'PL',
        name: 'Poland',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{2}-?\d{3}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'PT',
        name: 'Portugal',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}-?\d{3}$/,
        stateLabel: 'District',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'GR',
        name: 'Greece',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{3} ?\d{2}$/,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'IE',
        name: 'Ireland',
        postalCodeLabel: 'Eircode',
        postalCodePattern: /^[A-Z]\d{2} ?[A-Z0-9]{4}$/i,
        stateLabel: 'County',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'CZ',
        name: 'Czech Republic',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{3} ?\d{2}$/,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'HU',
        name: 'Hungary',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'County',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'RO',
        name: 'Romania',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{6}$/,
        stateLabel: 'County',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'RU',
        name: 'Russia',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{6}$/,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    // Asian Countries
    {
        code: 'CN',
        name: 'China',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{6}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'KR',
        name: 'South Korea',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'SG',
        name: 'Singapore',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{6}$/,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'MY',
        name: 'Malaysia',
        postalCodeLabel: 'Postcode',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'State',
        hasState: true,
        states: [
            'Johor', 'Kedah', 'Kelantan', 'Kuala Lumpur', 'Labuan', 'Malacca', 'Negeri Sembilan', 'Pahang',
            'Penang', 'Perak', 'Perlis', 'Putrajaya', 'Sabah', 'Sarawak', 'Selangor', 'Terengganu',
        ],
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'TH',
        name: 'Thailand',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'PH',
        name: 'Philippines',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'ID',
        name: 'Indonesia',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'VN',
        name: 'Vietnam',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'PK',
        name: 'Pakistan',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Province',
        hasState: true,
        states: [
            'Balochistan', 'Khyber Pakhtunkhwa', 'Punjab', 'Sindh', 'Gilgit-Baltistan', 'Azad Jammu and Kashmir',
        ],
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'BD',
        name: 'Bangladesh',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'Division',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'TR',
        name: 'Turkey',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'SA',
        name: 'Saudi Arabia',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}(-?\d{4})?$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'AE',
        name: 'United Arab Emirates',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^$/,
        stateLabel: 'Emirate',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'IL',
        name: 'Israel',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5,7}$/,
        stateLabel: 'District',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    // South American Countries
    {
        code: 'AR',
        name: 'Argentina',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^[A-Z]?\d{4}[A-Z]{0,3}$/i,
        stateLabel: 'Province',
        hasState: true,
        states: [
            'Buenos Aires', 'Catamarca', 'Chaco', 'Chubut', 'Córdoba', 'Corrientes', 'Entre Ríos', 'Formosa',
            'Jujuy', 'La Pampa', 'La Rioja', 'Mendoza', 'Misiones', 'Neuquén', 'Río Negro', 'Salta',
            'San Juan', 'San Luis', 'Santa Cruz', 'Santa Fe', 'Santiago del Estero', 'Tierra del Fuego', 'Tucumán',
        ],
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'CL',
        name: 'Chile',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{7}$/,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'CO',
        name: 'Colombia',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{6}$/,
        stateLabel: 'Department',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'PE',
        name: 'Peru',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'VE',
        name: 'Venezuela',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'State',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'EC',
        name: 'Ecuador',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{6}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    // Central American Countries
    {
        code: 'CR',
        name: 'Costa Rica',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'PA',
        name: 'Panama',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'Province',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'GT',
        name: 'Guatemala',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Department',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    // African Countries
    {
        code: 'ZA',
        name: 'South Africa',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'Province',
        hasState: true,
        states: [
            'Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo', 'Mpumalanga', 'Northern Cape', 'North West', 'Western Cape',
        ],
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'EG',
        name: 'Egypt',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'Governorate',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'NG',
        name: 'Nigeria',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{6}$/,
        stateLabel: 'State',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'KE',
        name: 'Kenya',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{5}$/,
        stateLabel: 'County',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    // Oceania Countries
    {
        code: 'NZ',
        name: 'New Zealand',
        postalCodeLabel: 'Postcode',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, unit, etc. (optional)',
    },
    {
        code: 'FJ',
        name: 'Fiji',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^$/,
        stateLabel: 'Division',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    // Additional Countries
    {
        code: 'IS',
        name: 'Iceland',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{3}$/,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'LU',
        name: 'Luxembourg',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'Canton',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'MT',
        name: 'Malta',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^[A-Z]{3} ?\d{2,4}$/i,
        stateLabel: 'Region',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
    {
        code: 'CY',
        name: 'Cyprus',
        postalCodeLabel: 'Postal Code',
        postalCodePattern: /^\d{4}$/,
        stateLabel: 'District',
        hasState: false,
        addressLine2Label: 'Apartment, etc. (optional)',
    },
];

// Default country config for countries not in the list
export const DEFAULT_COUNTRY_CONFIG: CountryConfig = {
    code: 'XX',
    name: 'Other',
    postalCodeLabel: 'Postal Code',
    stateLabel: 'State/Province',
    hasState: false,
    addressLine2Label: 'Apartment, suite, etc. (optional)',
};

export function getCountryConfig(countryName: string): CountryConfig {
    const country = COUNTRIES.find((c) => c.name === countryName);
    return country || DEFAULT_COUNTRY_CONFIG;
}

export function getCountryNames(): string[] {
    return COUNTRIES.map((c) => c.name).sort();
}

