// Common medical data for autocomplete suggestions
// These can be expanded or replaced with API calls in the future

export const COMMON_MEDICINES = [
    'Aspirin',
    'Ibuprofen',
    'Acetaminophen',
    'Metformin',
    'Lisinopril',
    'Amlodipine',
    'Omeprazole',
    'Simvastatin',
    'Albuterol',
    'Gabapentin',
    'Sertraline',
    'Metoprolol',
    'Losartan',
    'Atenolol',
    'Hydrochlorothiazide',
    'Furosemide',
    'Levothyroxine',
    'Amoxicillin',
    'Azithromycin',
    'Prednisone',
    'Warfarin',
    'Tramadol',
    'Oxycodone',
    'Morphine',
    'Insulin',
    'Atorvastatin',
    'Pantoprazole',
    'Montelukast',
    'Fluticasone',
    'Trazodone',
];

export const COMMON_ALLERGIES = [
    'Penicillin',
    'Sulfa drugs',
    'Aspirin',
    'Ibuprofen',
    'Codeine',
    'Latex',
    'Peanuts',
    'Tree nuts',
    'Shellfish',
    'Fish',
    'Eggs',
    'Milk',
    'Soy',
    'Wheat',
    'Dust mites',
    'Pollen',
    'Mold',
    'Pet dander',
    'Bee stings',
    'Ant bites',
    'Nickel',
    'Fragrances',
    'Sunscreen',
    'Topical antibiotics',
    'Adhesive tape',
];

export const COMMON_DIAGNOSES = [
    'Type 2 Diabetes',
    'Type 1 Diabetes',
    'Hypertension',
    'High Blood Pressure',
    'Asthma',
    'COPD',
    'Chronic Obstructive Pulmonary Disease',
    'Heart Disease',
    'Coronary Artery Disease',
    'Arthritis',
    'Rheumatoid Arthritis',
    'Osteoarthritis',
    'Osteoporosis',
    'Anxiety Disorder',
    'Depression',
    'Bipolar Disorder',
    'ADHD',
    'Attention Deficit Hyperactivity Disorder',
    'Epilepsy',
    'Migraine',
    'Hypothyroidism',
    'Hyperthyroidism',
    'Anemia',
    'Iron Deficiency Anemia',
    'Sleep Apnea',
    'GERD',
    'Gastroesophageal Reflux Disease',
    'Irritable Bowel Syndrome',
    'IBS',
    'Crohn\'s Disease',
    'Ulcerative Colitis',
    'Chronic Kidney Disease',
    'Liver Disease',
    'Hepatitis',
    'HIV',
    'Cancer',
    'Breast Cancer',
    'Lung Cancer',
    'Colon Cancer',
    'Prostate Cancer',
    'Eating Disorder',
    'Anorexia Nervosa',
    'Bulimia Nervosa',
    'Binge Eating Disorder',
    'PTSD',
    'Post-Traumatic Stress Disorder',
    'OCD',
    'Obsessive-Compulsive Disorder',
    'Schizophrenia',
    'Autism Spectrum Disorder',
    'Fibromyalgia',
    'Chronic Fatigue Syndrome',
    'Lupus',
    'Multiple Sclerosis',
    'Parkinson\'s Disease',
    'Alzheimer\'s Disease',
    'Dementia',
];

